// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvBfnmXD1ncPtTHmCupLz-ehYdygP-STk',
    appId: '1:155165877581:web:1d08f0110d736f11484304',
    messagingSenderId: '155165877581',
    projectId: 'asistenciaescolar-673cd',
    authDomain: 'asistenciaescolar-673cd.firebaseapp.com',
    storageBucket: 'asistenciaescolar-673cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWyYTwEJ043Nj6_YDgRxhcYu16f7JGPag',
    appId: '1:155165877581:android:1450a184544ccd6a484304',
    messagingSenderId: '155165877581',
    projectId: 'asistenciaescolar-673cd',
    storageBucket: 'asistenciaescolar-673cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeFX1P_OWNeE1iLcL-aStZdi6NNmRpcAs',
    appId: '1:155165877581:ios:5c77a8d7b246ba65484304',
    messagingSenderId: '155165877581',
    projectId: 'asistenciaescolar-673cd',
    storageBucket: 'asistenciaescolar-673cd.firebasestorage.app',
    iosBundleId: 'com.example.asistenciaEscolarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeFX1P_OWNeE1iLcL-aStZdi6NNmRpcAs',
    appId: '1:155165877581:ios:5c77a8d7b246ba65484304',
    messagingSenderId: '155165877581',
    projectId: 'asistenciaescolar-673cd',
    storageBucket: 'asistenciaescolar-673cd.firebasestorage.app',
    iosBundleId: 'com.example.asistenciaEscolarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvBfnmXD1ncPtTHmCupLz-ehYdygP-STk',
    appId: '1:155165877581:web:1d08f0110d736f11484304',
    messagingSenderId: '155165877581',
    projectId: 'asistenciaescolar-673cd',
    authDomain: 'asistenciaescolar-673cd.firebaseapp.com',
    storageBucket: 'asistenciaescolar-673cd.firebasestorage.app',
  );

}